#! /bin/sh

die() {
    printf '\n\033[31m✗\033[0m %s\n' "$*" >&2
    exit 1
}

success() {
    printf '\n\033[32m✓\033[0m %s\n' "$*"
}

info() {
    printf '\n\033[32m→\033[0m %s\n' "$*"
}

BASEDIR=$(dirname "$(readlink -f "$0")")

PLATFORM=linux-x64
OUTFOLDER="$BASEDIR/server-dist/$PLATFORM"

if command -v podman > /dev/null 2>&1; then
    container_run() { sudo podman "$@"; }
elif command -v docker > /dev/null 2>&1; then
    container_run() { sudo docker "$@"; }
else
    die "Install a container runtime"
fi

#[ -z "$DISCORDTOKEN" ] && die "DISCORDTOKEN not set"

info "Clear $OUTFOLDER" \
  && rm -fr "$BASEDIR/server-dist" \
  && cd "$BASEDIR" \
  && dotnet restore \
  && info "CD" \
  && cd "$BASEDIR/Credfeto.Nuget.Proxy.Server" \
  && info "Build Credfeto.Nuget.Proxy.Server" \
  && dotnet publish \
          --no-restore \
          -warnaserror \
          --configuration:Release \
          "-r:$PLATFORM" \
          --self-contained \
          -nodeReuse:False \
          "-p:Deterministic=True" \
          "-p:DisableSwagger=True" \
          "-p:FFPublishing=True" \
          "-p:IncludeNativeLibrariesForSelfExtract=True" \
          "-p:IsProduction=True" \
          "-p:NoWarn=NETSDK1179" \
          "-p:Optimize=true" \
          "-p:PublishAot=false" \
          "-p:PublishReadyToRun=False" \
          "-p:PublishReadyToRunShowWarnings=True" \
          "-p:PublishSingleFile=true" \
          "-p:SolutionDir=..\\" \
          "-p:SuppressNETCoreSdkPreviewMessage=true" \
          "-p:TreatWarningsAsErrors=True" \
          "-p:Version=2.0.1.179-main" \
          "-p:FFPublishing=True" \
          "-p:SolutionDir=..\\" \
          "-p:IsProduction=false" \
          --output "$OUTFOLDER" \
  && cd "$BASEDIR/server-dist/$PLATFORM" \
  && cp "$BASEDIR/../Dockerfile" . \
  && ls -lar \
  && container_run buildx build . -t "credfeto/nuget-proxy:test" \
  && container_run run \
      --name nuget-proxy \
      -it \
      --rm \
      -p 9080:8080/tcp \
      -p 9081:8081/tcp \
      -p 9081:8081/udp \
      -e Proxy__UpstreamUrl__0=https://api.nuget.org \
      -e Proxy__PublicUrl=https://localhost:9081 \
      -e Proxy__Packages=/cache \
      -v /cache/nuget-proxy-test:/cache \
      -v "$BASEDIR/Credfeto.Nuget.Proxy.Server/server.pfx:/usr/src/app/server.pfx" \
      "credfeto/nuget-proxy:test"
